# Generated by Django 5.1.4 on 2025-01-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
