# Generated by Django 5.1.4 on 2025-01-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_food_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="image",
            field=models.ImageField(default=1, upload_to="restaurant-images/"),
            preserve_default=False,
        ),
    ]
